'use client';
import {useEffect,useRef,useState}from'react';
import {accountTerms,type AccountTerms}from'@/lib/accountTerms';
import AccountPrivacy from './AccountPrivacy';
export default function TermsRequired({userId,terms,onRefresh,onSignOut}:{userId:string;terms:AccountTerms;onRefresh:()=>void;onSignOut:()=>void}){
 const[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>active.current?.abort(),[]);
 async function accept(){if(active.current||!checked)return;const controller=new AbortController();active.current=controller;setBusy(true);setError('');try{await accountTerms.account(userId,terms,undefined,controller.signal);if(!controller.signal.aborted)onRefresh();}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Acceptance is unavailable.');}finally{active.current=null;if(!controller.signal.aborted)setBusy(false);}}
 return <main className="min-h-screen bg-background px-6 py-12"><div className="mx-auto max-w-2xl space-y-6"><h1 className="text-3xl font-semibold">Review Arbor’s Terms</h1><p>Review version {terms.version} before normal account use. No acceptance has been inferred from signing in. You can still export your data, request deletion or contact support without accepting.</p><div className="max-h-96 overflow-y-auto rounded-xl border p-4" tabIndex={0} aria-label="Terms document"><h2>{terms.body.title}</h2><p>{terms.body.introduction}</p>{terms.body.sections.map(([heading,text])=><section key={heading}><h3 className="mt-4 font-semibold">{heading}</h3><p>{text}</p></section>)}</div><p><a href={`/terms/${encodeURIComponent(terms.version)}`} target="_blank" rel="noopener noreferrer">Open this Terms version</a> · <a href="/privacy" target="_blank" rel="noopener noreferrer">Privacy Notice</a></p><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/>I agree to Arbor’s Terms, version {terms.version}.</label><button className="entry-primary min-h-11" disabled={!checked||busy} onClick={()=>void accept()}>{busy?'Recording acceptance…':'Accept Terms and continue'}</button>{error&&<p role="alert">{error}</p>}<AccountPrivacy userId={userId}/><button className="entry-link min-h-11" onClick={onRefresh}>Refresh status</button><button className="entry-link min-h-11" onClick={onSignOut}>Sign out</button></div></main>;
}
