INTENTS = {
    "crypto": [
        "bitcoin",
        "btc",
        "ethereum",
        "eth",
        "crypto",
        "cryptocurrency",
    ],
    "retirement": [
        "retire",
        "financial freedom",
        "wealth",
        "millionaire",
        "become rich",
    ],
    "technology": [
        "technology",
        "tech",
        "nasdaq",
        "nasdaq-100",
        "innovation",
        "ai",
        "artificial intelligence",
    ],
    "semiconductors": [
        "semiconductor",
        "semiconductors",
        "chip",
        "chips",
        "nvidia",
        "amd",
        "tsmc",
    ],
    "market": [
        "voo",
        "s&p",
        "s&p 500",
        "sp500",
        "spy",
        "index fund",
        "market",
        "us market",
        "broad market",
    ],
    "comparison": [
        "vs",
        "versus",
        "compare",
        "difference between",
    ],
    "strength": [
        "strongest",
        "strength",
        "best holding",
        "largest holding",
        "top holding",
        "best investment",
    ],
    "ownership": [
        "why do i own",
        "why own",
        "why is",
        "why did you choose",
        "purpose of",
    ],
    "portfolio_strategy": [
        "why is my portfolio",
        "why did you build my portfolio",
        "why is my portfolio built this way",
        "explain my portfolio",
        "portfolio strategy",
        "portfolio design",
        "how is my portfolio structured",
        "why these investments",
    ],
}
