INTENTS = {
    "crypto": [
        "bitcoin",
        "btc",
        "ethereum",
        "eth",
        "crypto",
        "cryptocurrency",
    ],
    "retirement": [
        "retire",
        "financial freedom",
        "millionaire",
        "become rich",
    ],
    "technology": [
        "technology",
        "tech",
        "nasdaq",
        "nasdaq-100",
        "innovation",
        "ai",
        "artificial intelligence",
    ],
    "semiconductors": [
        "semiconductor",
        "semiconductors",
        "chip",
        "chips",
        "nvidia",
        "amd",
        "tsmc",
    ],
    "market": [
        "voo",
        "s&p",
        "s&p 500",
        "sp500",
        "spy",
        "index fund",
        "market",
        "us market",
        "broad market",
    ],
    "comparison": [
        "vs",
        "versus",
        "compare",
        "difference between",
    ],
    "strength": [
        "strongest",
        "strength",
        "best holding",
        "largest holding",
        "top holding",
        "best investment",
    ],
    "ownership": [
        "why do i own",
        "why own",
        "why is",
        "why did you choose",
        "purpose of",
    ],
    "portfolio_strategy": [
        "why is my portfolio",
        "why did you build my portfolio",
        "why is my portfolio built this way",
        "explain my portfolio",
        "portfolio strategy",
        "portfolio design",
        "how is my portfolio structured",
        "why these investments",
    ],
    "overlap": [
        "overlap",
        "overlapping",
        "do i own too much",
        "too much exposure",
        "too concentrated",
        "concentrated",
        "both qqqm and smh",
        "both voo and qqqm",
        "both qqqm and voo",
        "both voo and smh",
        "both smh and qqqm",
        "why do i have both",
        "why own both",
        "why do i own both",
    ],
}
