import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {withAuthenticatedBrowser} from './auth.mjs';
import {origin,setup,fixtureControls,portfolio} from './ux-fixture.mjs';
const out='/tmp/arbor-sheets-captures';await mkdir(out,{recursive:true});
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,PUT,POST,OPTIONS'};
const row={id:'00000000-0000-4000-8000-000000000801',holding_id:portfolio.holdings[0].id,product_id:'gotrade_vt',provider:'gotrade',investment_date:'2026-09-24',units:'0.8',amount_paid_php:'8000.00',recorded_at:'2026-09-24T00:00:00Z',updated_at:'2026-09-24T00:00:00Z',revision:7,voided_at:null};
let providerIntents=0,providerNavigations=0,goalWrites=0,editWrites=0,voidWrites=0,goalStatus=200,editStatus=200,voidStatus=200,errors=0;const checks=[];
async function intercepted(context){await setup(context);await context.route('https://www.heygotrade.com/**',async route=>{providerNavigations++;return route.fulfill({status:200,contentType:'text/html',body:'<title>Synthetic provider destination</title>'});});await context.route('**/v2/**',async route=>{
 const r=route.request(),url=new URL(r.url()),path=url.pathname;const json=(body,status=200)=>route.fulfill({json:body,status,headers});
 if(r.method()==='OPTIONS')return route.fulfill({status:204,headers});
 if(path.endsWith('/v2/pending-recordings')&&r.method()==='POST'){providerIntents++;const b=r.postDataJSON();assert.equal(b.provider,'gotrade');return json({id:'00000000-0000-4000-8000-000000000999',product_id:b.product_id,provider:b.provider,source:'monthly',status:'pending',started_at:'2026-10-03T00:00:00Z',resolved_at:null});}
 if(path.includes('/admin/'))return json({allowed:false});
 if(path==='/v2/goal'){goalWrites++;const b=r.postDataJSON();assert.deepEqual(Object.keys(b).sort(),['expected_revision','goal_date','goal_name','goal_target']);assert.equal(b.expected_revision,fixtureControls.plan.revision);if(goalStatus!==200)return json({detail:'Synthetic goal conflict'},goalStatus);Object.assign(fixtureControls.plan.profile,{goal_name:b.goal_name,goal_date:b.goal_date,goal_target:b.goal_target});fixtureControls.plan.revision='9'.repeat(64);return json(fixtureControls.plan);}
 if(path.endsWith('/portfolio/entries')&&r.method()==='GET'&&url.searchParams.get('holding_id'))return json({entries:[row],page:0,has_more:false});
 if(path.endsWith('/entries/'+row.id)&&r.method()==='PUT'){editWrites++;const b=r.postDataJSON();assert.equal(b.expected_revision,7);assert.equal('unit_price'in b,false);if(editStatus!==200)return json({detail:'Synthetic revision conflict'},editStatus);return json({});}
 if(path.endsWith('/entries/'+row.id+'/void')){voidWrites++;assert.deepEqual(r.postDataJSON(),{expected_revision:7});if(voidStatus!==200)return json({detail:'Synthetic conflict'},voidStatus);return json({});}
 return route.fallback();
 });}
await withAuthenticatedBrowser(async({page})=>{
 page.on('pageerror',()=>errors++);
 await page.goto(origin+'/#login');await page.getByLabel('Email address').fill('phase2b@example.test');await page.getByLabel('Password').fill('fixture-only-password');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByRole('heading',{name:'Hello, Maya.'}).waitFor();
 const go=async hash=>{await page.evaluate(h=>{location.hash=h;},hash);await page.waitForTimeout(100);};
 const sheet=name=>page.getByRole('dialog',{name,exact:true});
 const shot=async name=>{await page.waitForTimeout(120);await page.screenshot({path:out+'/'+name+'.png'});};
 const focused=async d=>assert.equal(await d.locator('.sheet-header h2').evaluate(n=>document.activeElement===n),true);
 const close=async(d,hash)=>{await d.getByRole('button',{name:'Close',exact:true}).click();await page.waitForFunction(h=>location.hash===h,hash);await d.waitFor({state:'hidden'});};
 const fit=async d=>{const b=await d.boundingBox();assert.ok(b.x>=-1&&b.y>=-1&&b.x+b.width<=await page.evaluate(()=>innerWidth)+1);assert.equal(await d.evaluate(n=>n.scrollWidth>n.clientWidth),false);};
 for(const width of [320,375,768,1440])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:width===1440?1000:844});await page.emulateMedia({colorScheme:theme});
  await go('home');await page.locator('.home-next-investment').click();let d=sheet('Investment breakdown');await d.waitFor();await focused(d);await fit(d);await d.getByLabel('Amount to split (PHP)').fill('17000');await shot(`breakdown-${width}-${theme}`);await close(d,'#home');await page.waitForFunction(()=>document.querySelector('.home-next-investment')===document.activeElement);
  await go('portfolio');await page.locator('.portfolio-planning-tools a[href="#portfolio/contribution"]').click();await d.waitFor();assert.equal(await d.getByLabel('Amount to split (PHP)').inputValue(),'17000');assert.equal(await page.locator('.monthly-investing').count(),1);await page.keyboard.press('Escape');await d.waitFor({state:'hidden'});await page.waitForFunction(()=>location.hash==='#portfolio');
  await page.locator('.portfolio-planning-tools a[href="#portfolio/what-if"]').click();d=sheet('What-if');await d.waitFor();await focused(d);await fit(d);await d.getByLabel('Monthly amount to explore (PHP)').fill('18000');await d.locator('.what-if-result').waitFor();await shot(`what-if-${width}-${theme}`);await close(d,'#portfolio');
  await go('settings');await page.locator('a[href="#settings/plan"]').click();d=sheet('Your plan');await d.waitFor();await focused(d);await fit(d);await shot(`settings-plan-${width}-${theme}`);await close(d,'#settings');
  await page.locator('a[href="#settings/goal"]').click();d=sheet('Your goal');await d.waitFor();await focused(d);assert.equal(await d.getByLabel('Goal name').inputValue(),'A place of my own');await fit(d);await shot(`settings-goal-${width}-${theme}`);await close(d,'#settings');
  await go('portfolio');await page.getByRole('button',{name:'View Vanguard Total World Stock ETF',exact:true}).click();const parent=sheet('VT');await parent.waitFor();await parent.getByRole('button',{name:'Edit',exact:true}).click();d=sheet('Edit investment');await d.waitFor();assert.equal(await d.getByLabel('Investment date').evaluate(n=>n===document.activeElement),true);assert.equal(await d.getByLabel('Units received').inputValue(),'0.8');assert.equal(await d.getByLabel('Actual paid (PHP, optional)').inputValue(),'8000.00');await fit(d);await shot(`holding-edit-${width}-${theme}`);await d.getByRole('button',{name:'Cancel',exact:true}).click();await d.waitFor({state:'hidden'});assert.equal(await parent.getByRole('button',{name:'Edit',exact:true}).evaluate(n=>n===document.activeElement),true);
  await parent.getByRole('button',{name:'Delete',exact:true}).click();d=sheet('Delete investment?');await d.waitFor();await focused(d);await fit(d);await shot(`holding-delete-${width}-${theme}`);for(const text of ['Cancel','Delete investment']){const b=await d.getByRole('button',{name:text,exact:true}).boundingBox();assert.ok(b.y+b.height<=await page.evaluate(()=>innerHeight),text);}await page.keyboard.press('Escape');await d.waitFor({state:'hidden'});assert.equal(await parent.isVisible(),true);await parent.getByRole('button',{name:'Close',exact:true}).click();checks.push({width,theme,sharedDraft:true,planGoalDirect:true,holdingActionsFocused:true});
 }
 // Nested Plan → What-if Back restores Plan's own opener, then closes to Settings.
 await go('settings');await page.locator('a[href="#settings/plan"]').click();let d=sheet('Your plan');await d.waitFor();await d.getByRole('link',{name:/Explore What-if/}).click();await sheet('What-if').waitFor();await close(sheet('What-if'),'#settings/plan');await d.waitFor();await close(d,'#settings');
 // Goal uses the single existing save contract, preserves values and rejects conflicts.
 await page.locator('a[href="#settings/goal"]').click();d=sheet('Your goal');await d.getByLabel('Goal name').fill('Synthetic updated goal');await d.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await d.getByLabel('Target amount (future PHP)').inputValue(),'3000000');await d.getByLabel('Target amount (future PHP)').fill('0');assert.equal(await d.getByRole('button',{name:'Continue',exact:true}).isDisabled(),true);await d.getByLabel('Target amount (future PHP)').fill('3100000');await d.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await d.getByLabel('Target date (optional)').inputValue(),'2036-09-30');goalStatus=409;await d.getByRole('button',{name:'Save goal',exact:true}).click();await d.getByRole('alert').waitFor();await shot('goal-conflict');goalStatus=200;await d.getByRole('button',{name:'Save goal',exact:true}).click();await d.waitFor({state:'hidden'});await page.waitForFunction(()=>location.hash==='#settings');assert.equal(goalWrites,2);
 // Edit conflict stays in the action sheet; retry remains the exact existing revision payload.
 await go('portfolio');await page.getByRole('button',{name:'View Vanguard Total World Stock ETF',exact:true}).click();let parent=sheet('VT');await parent.getByRole('button',{name:'Edit',exact:true}).click();d=sheet('Edit investment');await d.getByLabel('Units received').fill('0');assert.equal(await d.getByRole('button',{name:'Review correction',exact:true}).isDisabled(),true);await d.getByLabel('Units received').fill('0.9');await d.getByRole('button',{name:'Review correction',exact:true}).click();editStatus=409;await d.getByRole('button',{name:'Confirm correction',exact:true}).click();await d.getByRole('alert').waitFor();await shot('edit-conflict');await d.getByRole('button',{name:'Cancel',exact:true}).click();await parent.getByRole('button',{name:'Delete',exact:true}).click();d=sheet('Delete investment?');voidStatus=409;await d.getByRole('button',{name:'Delete investment',exact:true}).click();await d.getByRole('alert').waitFor();await shot('delete-conflict');await d.getByRole('button',{name:'Cancel',exact:true}).click();await parent.getByRole('button',{name:'Close',exact:true}).click();
 // Calculation, scoped recording and browser Back close the nested dialog with its parent.
 await go('home');await page.locator('.home-next-investment').click();d=sheet('Investment breakdown');await d.getByLabel('Amount to split (PHP)').fill('15000');await d.getByRole('button',{name:'See investment breakdown',exact:true}).click();await d.getByRole('region',{name:'Monthly investment breakdown'}).waitFor();await d.getByRole('button',{name:'Record investment',exact:true}).first().click();await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===2);await shot('nested-recording');await page.keyboard.press('Escape');assert.equal(await d.isVisible(),true);await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===1);await page.goBack();await d.waitFor({state:'hidden'});assert.equal(await page.locator('dialog[open]').count(),0);
 // Keyboard traps and fresh direct bookmarks close to the correct destination.
 await page.setViewportSize({width:375,height:844});
 for(const [hash,title,fallback] of [['settings/plan','Your plan','#settings'],['settings/goal','Your goal','#settings'],['portfolio/what-if','What-if','#portfolio'],['portfolio/contribution','Investment breakdown','#portfolio'],['home/monthly','Investment breakdown','#home'],['plan','Your plan','#home']]){
  await page.goto(origin+'/#'+hash);await page.evaluate(()=>history.replaceState(null,'',location.href));await page.reload();d=sheet(title);await d.waitFor();await focused(d);await page.keyboard.press('Shift+Tab');assert.equal(await d.evaluate(n=>n.contains(document.activeElement)),true);await page.keyboard.press('Tab');assert.equal(await d.getByRole('button',{name:'Close',exact:true}).evaluate(n=>n===document.activeElement),true);await close(d,fallback);
 }
 // Provider intent precedes a locally fulfilled destination; zero vendor network calls.
 await go('home');await page.locator('.home-next-investment').click();d=sheet('Investment breakdown');await d.getByLabel('Amount to split (PHP)').fill('15000');await d.getByRole('button',{name:'See investment breakdown',exact:true}).click();await d.locator('.monthly-breakdown').waitFor();const popupPromise=page.waitForEvent('popup');await d.getByRole('button',{name:'Continue with Gotrade (opens in a new tab)',exact:true}).first().click();const popup=await popupPromise;await popup.waitForURL('https://www.heygotrade.com/');assert.equal(providerIntents,1);assert.equal(providerNavigations,1);assert.equal(fixtureControls.recordingCounts().entryPosts,0);await popup.close();
 // Choosing an investment is a child Sheet; Escape retains the parent and draft.
 await d.getByRole('button',{name:'Change investment',exact:true}).first().click();await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===2);await shot('nested-choice');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===1);assert.equal(await d.getByLabel('Amount to split (PHP)').inputValue(),'15000');
 // Recording retains the scoped catalogue and sends only actual supplied fields.
 await d.getByRole('button',{name:'Record investment',exact:true}).first().click();let record=sheet('Record an investment');await record.waitFor();assert.equal(await record.locator('[data-product="gotrade_vt"]').count(),0);await record.locator('[data-product="gotrade_vgt"]').click();record=sheet('Record VGT investment');await record.waitFor();await record.getByLabel('Total units purchased').fill('1');await record.getByLabel('Total amount paid (PHP)',{exact:true}).fill('2000');await record.getByRole('button',{name:'Review investment',exact:true}).click();await record.getByRole('button',{name:'Confirm and save',exact:true}).click();await record.waitFor({state:'hidden'});assert.equal(await d.isVisible(),true);await d.getByText('Investment recorded',{exact:true}).waitFor();assert.equal(fixtureControls.recordingCounts().entryPosts,1);await close(d,'#home');
 // Successful correction/deletion responses close both action and parent views.
 await go('portfolio');await page.getByRole('button',{name:'View Vanguard Total World Stock ETF',exact:true}).click();parent=sheet('VT');await parent.getByRole('button',{name:'Edit',exact:true}).click();d=sheet('Edit investment');await d.getByLabel('Units received').fill('0.9');await d.getByRole('button',{name:'Review correction',exact:true}).click();editStatus=200;await d.getByRole('button',{name:'Confirm correction',exact:true}).click();await parent.waitFor({state:'hidden'});await page.getByRole('button',{name:'View Vanguard Total World Stock ETF',exact:true}).click();parent=sheet('VT');await parent.getByRole('button',{name:'Delete',exact:true}).click();d=sheet('Delete investment?');voidStatus=200;await d.getByRole('button',{name:'Delete investment',exact:true}).click();await parent.waitFor({state:'hidden'});
 // Short viewport: content is scrollable and destructive controls remain reachable.
 await page.setViewportSize({width:375,height:520});await go('portfolio');await page.getByRole('button',{name:'View Vanguard Total World Stock ETF',exact:true}).click();parent=sheet('VT');await parent.getByRole('button',{name:'Delete',exact:true}).click();d=sheet('Delete investment?');await d.waitFor();await d.getByRole('button',{name:'Delete investment',exact:true}).scrollIntoViewIfNeeded();await shot('delete-short-height');await page.keyboard.press('Escape');await parent.getByRole('button',{name:'Close',exact:true}).click();
 // Free gate remains a modal and never mounts the Plus calculation form.
 fixtureControls.setFree(true);await go('settings');await page.reload();await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();await go('home');await page.locator('.home-next-investment').click();d=sheet('Investment breakdown');await d.waitFor();assert.equal(await d.getByLabel('Amount to split (PHP)').count(),0);await shot('free-breakdown-gate');await close(d,'#home');
 assert.equal(errors,0);assert.equal(fixtureControls.getBlocked(),0);assert.equal(fixtureControls.recordingCounts().entryPosts,1);
 const evidence={checks,directBookmarks:6,keyboardTrap:true,providerIntents,providerNavigations,vendorNetworkCalls:0,syntheticPurchase:1,successActionResponses:true,goalWrites,editWrites,voidWrites,allWritesSynthetic:true,hostedWrites:0,pageErrors:errors,unexpectedExternal:fixtureControls.getBlocked(),nestedBack:true,nestedEscape:true,goalSaveContract:true,revisionConflictsInFocusedView:true,freeGate:true,shortViewportScrollable:true,recordingScoped:true};await writeFile(out+'/evidence.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));
},{syntheticFixture:{baseURL:origin,setup:intercepted}});
