/** Public beta information. No account behavior or policy enforcement lives here. */
export const publicInformation = {
  privacy: {
    title: "Privacy",
    introduction: "How information supports the current Arbor beta.",
    sections: [
      ["Operator and contact", "Arbor is currently operated by Jonathan Isidoro, operating Arbor. Jonathan handles privacy questions and requests through support@arbor.ph."],
      ["Information you provide", "Account access uses your email and password through Supabase Auth. Your saved profile can include your name, country, currency, financial-readiness answers, goal, timeline, selected approach and preferences. Investment records include the products, providers, dates, units and actual PHP amounts you enter. Arbor also stores reference-value history, monthly check-ins and unfinished provider recordings used by its tools."],
      ["How Arbor uses information", "Arbor uses account information to restore your account and saved plan, calculate and display your recorded portfolio, plan contributions and explain your choices. Ask Arbor sends your question to the Arbor backend. Its current explanations use deterministic calculations and templates, with your saved plan and, where needed, recorded portfolio information; the current question-processing path does not call an external AI model. Do not include passwords, bank details or other sensitive information in a question."],
      ["Services supporting the beta", "Supabase provides authentication and database services. Vercel hosts the frontend website and application; Render hosts the backend application services and workers. Resend supports product reminder email delivery; eligible unfinished recordings can prompt a generic reminder sent to your account email. Zoho Mail handles correspondence sent to support@arbor.ph. Provider websites you choose to visit have their own privacy practices. Arbor does not connect to your brokerage account or ask for its password."],
      ["Browser storage", "The application stores its sign-in session in browser storage through the authentication client, and remembers your appearance preference locally. These support account access and presentation. These public pages do not add analytics or advertising trackers."],
      ["Corrections, records and deletion", "You can correct supported investment records in Arbor. Deleting an investment entry removes it from active calculations but retains an audit record; it does not delete your account or all associated data. There is currently no self-service whole-account deletion action. For access, correction, portability, objection or erasure questions, contact support@arbor.ph. Requests require assessment under applicable law and the account-data process; this page does not promise immediate or permanent erasure."],
      ["Privacy requests and retention", "Jonathan receives privacy requests at support@arbor.ph, verifies the requester's identity using proportionate information, reviews the applicable rights and explains what can be provided, corrected or deleted. The current investment ledger prevents deleting an account with ledger history, so complete erasure is not promised. Audit records are not exempt from deletion review or retained indefinitely without a justified reason. Account and plan information is kept while needed to provide the service, with retention assessed when closure is requested. Any continued hold must have a specific justified purpose. Arbor has adopted future targets of 30 days after resolution for reminder-delivery metadata and six months after resolution for ordinary support correspondence. These targets are not currently implemented automatic purges or fixed deletion promises. Privacy-request records are assessed separately and limited to what is needed for accountability."],
      ["Provider locations, logs and backups", "The configured primary Supabase project region is ap-northeast-1 (Japan), and the Render application services are configured in Singapore. These settings do not establish where every provider processes or stores information. Vercel, Resend and Zoho processing locations, international-transfer arrangements, log windows and backup or export retention have not all been verified. Provider copies and technical deletion processes require assessment when responding to a request; no universal storage location or fixed backup-erasure deadline is promised."],
      ["About this notice", "This notice explains the current beta and its known limitations. It is not a request for blanket consent or a claim of legal certification. Questions about processing grounds, provider handling or your applicable privacy rights can be sent to support@arbor.ph. No security certification, data-sale policy or AI-training exclusion is claimed here."],
    ],
  },
  terms: {
    title: "Terms",
    introduction: "The boundaries of the current private beta.",
    sections: [
      ["Operator and contact", "The current operator is Jonathan Isidoro, operating Arbor. Contact support@arbor.ph for questions about the beta."],
      ["Beta eligibility", "The beta is for people aged 18 or older in the Philippines. This is the beta eligibility policy; Arbor does not currently verify age."],
      ["What Arbor provides", "Arbor is a planning, tracking and education companion. You choose your approach and investments. Arbor calculates, tracks and explains. It does not hold money, execute trades, open provider accounts or automatically synchronize brokerage transactions."],
      ["Your account and records", "Protect account access and provide accurate information. Record actual investments from your provider records, including units received and the amount paid. A planned amount, unfinished provider recording or monthly check-in is not proof that an investment occurred. Do not submit brokerage credentials or someone else's private financial information."],
      ["Investment decisions", "You decide whether to follow a calculated breakdown. Information and explanations are not personalized buy/sell instructions. Verify provider eligibility, fees, minimums, execution details and current product documents before investing. Provider references identify supported paths and imply no partnership or endorsement."],
      ["Values, projections and explanations", "Reference values can be delayed, incomplete or unavailable and can differ from execution prices. Contributions are not investment profit. Projections use planning assumptions and are hypothetical; they do not guarantee results. Explanations can be mistaken. Use your provider records to verify transactions and seek qualified advice where needed."],
      ["Beta availability", "Private-beta members currently receive an Arbor Plus trial. Monthly contribution planning, Plan Alignment, Projection & What If and deeper portfolio-aware explanations are Plus capabilities. Subscription checkout and public Free access are not active. Get started opens account creation. No trial duration, future price, billing date or automatic conversion is promised here."],
      ["Service availability and responsible use", "Arbor is a beta service. Features and availability may change, and interruptions may occur. Use the service lawfully and respect other people's account access and privacy. Access may be restricted where necessary to protect accounts, prevent misuse or meet applicable legal requirements. Contact support@arbor.ph about an access concern."],
      ["Responsibility and complaints", "You remain responsible for your investment decisions and for verifying records against your provider. Philippine law governs these intended beta conditions. Contact support@arbor.ph first about a concern so Jonathan can review it. This does not require arbitration or prevent you from exercising statutory rights or approaching an appropriate authority. Nothing here excludes rights or responsibilities that applicable law does not permit to be excluded."],
      ["About these terms", "These are Arbor's intended conditions for the beta. Publishing this page does not establish that an existing user has accepted it. The current account flow does not record affirmative acceptance of a Terms version. No payment obligation, fixed trial duration or automatic paid conversion is created by this page."],
    ],
  },
  "investment-disclosures": {
    title: "Investment disclosures",
    introduction: "Useful calculations, with decisions kept in your hands.",
    sections: [
      ["Role and risk", "Arbor is not a broker, bank, custodian or exchange. Investments can lose value. Market, concentration, currency and provider risks can affect results. No investment return, goal outcome or ability to sell at a displayed value is guaranteed."],
      ["Recorded value and gain", "Portfolio value uses the holdings you recorded and the available reference values. Adding capital may increase portfolio value without creating profit. Gain/loss against recorded cost requires complete cost information. Chart gain/loss belongs to the selected period and is distinct from cumulative holding gain. Missing context is not reconstructed as a known profit."],
      ["Currency and history", "PHP and USD portfolio views use available exchange-rate context. Currency changes can affect displayed values. Chart coverage depends on supportable records and reference data; a range label does not promise complete data for that entire period."],
      ["Planning illustrations", "Monthly planning uses your chosen targets and current values; you review the breakdown and decide whether to follow it. Projection and What If use stated assumptions rather than a forecast. Planned contributions are not executed investments or recorded cost."],
      ["Providers and examples", "Arbor supports a curated set of products. Confirm availability and requirements with your provider. Names and marks are used for identification, with no partnership implied. Website product images use one isolated synthetic scenario and illustrate the interface, not actual customer investment performance."],
    ],
  },
} as const;
export type PublicInformationPage = keyof typeof publicInformation;
