'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {deletionReviewApi,deletionReviewResult,deletionManualGuidance,type DeletionPage,type DeletionReview as Review} from '@/lib/adminDeletionReview';
import {AdminAccessError} from '@/lib/ownerAdmin';
const date=(v:string|null)=>v?new Date(v).toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}):'Not recorded';
const words=(v:string)=>v.replaceAll('_',' ');
export default function DeletionReview({userId,onBack}:{userId:string;onBack:()=>void}){
 const [page,setPage]=useState<DeletionPage|null>(null),[selected,setSelected]=useState<Review|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[allowed,setAllowed]=useState<boolean|null>(null);
 const mounted=useRef(false),pending=useRef(false),heading=useRef<HTMLHeadingElement>(null),feedback=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const load=useCallback(async(offset=0,id?:string)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const permit=await deletionReviewApi.access(userId);if(!mounted.current)return;setAllowed(permit);if(!permit){setPage(null);setSelected(null);return;}const value=id?await deletionReviewApi.detail(userId,id):await deletionReviewApi.list(userId,offset);if(!mounted.current)return;if(id)setSelected(value as Review);else{setPage(value as DeletionPage);setSelected(null);}}catch(cause){if(mounted.current){if(cause instanceof AdminAccessError){setAllowed(false);setPage(null);setSelected(null);}setError(cause instanceof Error?cause.message:'Deletion review is unavailable.');}}finally{pending.current=false;if(mounted.current)setBusy(false);}},[userId]);
 useEffect(()=>{queueMicrotask(()=>{if(mounted.current)void load();});},[load]);
 useEffect(()=>{heading.current?.focus();},[selected?.request_id]);
 useEffect(()=>{if(error)feedback.current?.focus();},[error]);
 return <section className="owner-admin" aria-label="Account-deletion review"><button className="entry-link min-h-11" onClick={onBack}>‹ Investment requests</button><p className="eyebrow">Read only</p><h2 tabIndex={-1} ref={heading}>Account-deletion requests</h2><p className="admin-intro">Review canonical requests, holds and manual checkpoints. This page cannot delete accounts or mark deletion complete.</p>
 {allowed===null&&!error&&<p role="status">Checking deletion review access…</p>}{allowed===false&&<p role="status">Account-deletion review is unavailable for this account.</p>}{error&&<p ref={feedback} tabIndex={-1} role="alert">{error}</p>}
 {(allowed===true||error)&&<button className="entry-link min-h-11" disabled={busy} onClick={()=>void load(page?.offset??0,selected?.request_id)}>{busy?'Loading…':'Refresh deletion requests'}</button>}
 {allowed===true&&selected?<><button className="entry-link min-h-11" disabled={busy} onClick={()=>void load(page?.offset??0)}>‹ All deletion requests</button><article className="admin-card"><h3>{deletionReviewResult(selected)}</h3><p className="admin-note">Request {selected.request_id}</p><dl><div><dt>Requested · PHT</dt><dd>{date(selected.requested_at)}</dd></div><div><dt>Request</dt><dd>{words(selected.request_status)}</dd></div><div><dt>Account access state</dt><dd>{selected.lifecycle_state?words(selected.lifecycle_state):'Account record unavailable'}</dd></div>{selected.withdrawn_at&&<div><dt>Withdrawn · PHT</dt><dd>{date(selected.withdrawn_at)}</dd></div>}<div><dt>Manual checkpoint</dt><dd>{words(selected.processing_state)}</dd></div><div><dt>Identity reviewed · PHT</dt><dd>{date(selected.verified_at)}</dd></div></dl>
 <h4 className="mt-5 font-semibold">Holds</h4>{selected.holds.length?<ul>{selected.holds.map((hold,i)=><li className="admin-hold" key={i}><strong>{words(hold.category)} · {words(hold.reason)}</strong><p>Review {date(hold.review_at)} PHT · End {date(hold.end_at)} PHT</p></li>)}</ul>:<p className="admin-note">No holds recorded. This does not authorize deletion.</p>}
 {selected.receipt_id&&<section className="admin-receipt" aria-label="Verified deletion receipt"><h4 className="font-semibold">Verified active-system receipt</h4><p>{selected.receipt_id}</p><p>Confirmed {date(selected.completed_at)} PHT</p><p>{selected.provider_status==='pending_copies'?'Provider copies remain pending.':'Provider-copy assessment confirmed.'} This is not a claim that every copy is erased.</p><p>Receipt available until {date(selected.receipt_expires_at)} PHT. Message delivery is not confirmed here.</p></section>}
 <details className="mt-5"><summary className="entry-link min-h-11">Manual procedure</summary><p className="admin-note">{deletionManualGuidance(selected)}</p><p className="admin-note">Use the existing operator procedure for project/request/identity binding, per-phase approval, fresh inventory and session/Storage/Auth confirmation. Keep legal/restore holds and provider-copy assessment intact; stop on stale or uncertain evidence.</p></details></article></>:allowed===true&&page?<section className="admin-card"><h3>Deletion requests</h3>{!page.items.length&&<p>No account-deletion requests available.</p>}{page.items.map(row=><button className="admin-request-row admin-deletion-row" key={row.request_id} disabled={busy} onClick={()=>void load(page.offset,row.request_id)}><strong>{deletionReviewResult(row)}</strong><span>Request {row.request_id.slice(0,8)}</span><time dateTime={row.requested_at??undefined}>{date(row.requested_at)}</time><span className="admin-badge">{row.holds.length?'Hold recorded':'Read only'}</span></button>)}<div className="admin-pagination">{page.offset>0&&<button className="entry-link min-h-11" disabled={busy} onClick={()=>void load(Math.max(0,page.offset-50))}>Previous</button>}{page.has_more&&page.offset<10000&&<button className="entry-link min-h-11" disabled={busy} onClick={()=>void load(page.offset+50)}>Next</button>}</div></section>:null}
 </section>;
}
